CREATE TABLE member (
    id number generated by default on null as identity, 
    -- generated ~ identity: AUTOINCREMENT 같은 기능
    name varchar2(100) not null,
    passwd varchar2(50) not null);

SELECT * FROM DUAL;

SELECT * FROM tab;

-- 유저 데이터베이스 이것저것 확인
SELECT * FROM user_objects;
SELECT * FROM user_tables;
SELECT * FROM user_views;
SELECT * FROM user_sequences;

DESC member;

alter table member add phone varchar2(100);

alter table member drop column phone;

rename member to member2;
rename member2 to member;

ALTER TABLE member add constraint pk_member primary key (id);

INSERT INTO member (name, passwd)
VALUES ('홍길동', '1234');
-- autoincrement 등 자동으로 입력되는 값이 있으면 컬럼명을 꼭 넣어줘야 함.

SELECT last_name, salary FROM employees;

SELECT last_name AS "사원 명", salary * 12 "연봉" FROM employees;

-- 연봉 = salary + (salary * commision_pct)

SELECT last_name, salary * 12 + (salary * NVL(commission_pct, 0)) FROM employees;

SELECT last_name FROM employees WHERE manager_id IS NULL;

DROP TABLE member purge;

CREATE TABLE member(
    id VARCHAR2(20) PRIMARY KEY,
    passwd VARCHAR2(20), 
    name VARCHAR2(30));
    
SELECT * FROM member;

CREATE TABLE XCI_MEMBERS (
USERNAME VARCHAR2(20) PRIMARY KEY, -- 사용자 ID
PASSWORD VARCHAR2(100) NOT NULL,  -- 비밀번호
NAME VARCHAR2(100) NOT NULL, EMAIL VARCHAR2(100) NOT NULL, BIRTH NUMBER(4) NOT NULL, JOIN_DATE DATE DEFAULT SYSDATE
-- 사용자 실제 이름
-- 이메일
-- 생년
-- 가입 날짜, 기본값은 현재 날짜
);

INSERT INTO XCI_MEMBERS (USERNAME, PASSWORD, NAME, EMAIL, BIRTH, JOIN_DATE)
VALUES ('yujin', 'pass', '안유진', 'yujin@ive.com', 2003, TO_DATE('2021-11-01', 'YYYY-MM-DD'));
INSERT INTO XCI_MEMBERS (USERNAME, PASSWORD, NAME, EMAIL, BIRTH, JOIN_DATE)
VALUES ('ga_eul', 'pass', '가을', 'gaeul@ive.com', 2002, TO_DATE('2021-11-01', 'YYYY-MM-DD'));
INSERT INTO XCI_MEMBERS (USERNAME, PASSWORD, NAME, EMAIL, BIRTH, JOIN_DATE)
VALUES ('rei', 'pass', '레이', 'rei@ive.com', 2004, TO_DATE('2021-11-01', 'YYYY-MM-DD'));
INSERT INTO XCI_MEMBERS (USERNAME, PASSWORD, NAME, EMAIL, BIRTH, JOIN_DATE)
VALUES ('z10', 'z10', '장원영', '10zang@ive.com', 2004, TO_DATE('2021-11-01', 'YYYY-MM-DD'));
INSERT INTO XCI_MEMBERS (USERNAME, PASSWORD, NAME, EMAIL, BIRTH, JOIN_DATE)
VALUES ('liz', 'pass', '리즈', 'liz@ive.com', 2004, TO_DATE('2021-11-01', 'YYYY-MM-DD'));
INSERT INTO XCI_MEMBERS (USERNAME, PASSWORD, NAME, EMAIL, BIRTH, JOIN_DATE)
VALUES ('leeseo', 'pass', '이서', 'leeseo@ive.com', 2007, TO_DATE('2021-11-01', 'YYYY-MM-DD'));
COMMIT;

SELECT * FROM member;

